[env]
_.python.venv = { path = ".venv", create = false }

[settings]
experimental = true

[tools]
"jq" = "latest"
"npm:cwebp-bin" = "latest"

[tasks.serve]
description = "Serve the site locally"
run = "retype start"

[tasks.format]
description = "Format files"
run = "dprint fmt --incremental=true --allow-no-files"
alias = "fmt"

[tasks."recipe-scrapers:install"]
description = "Installs recipe-scrapers via rye"
run = """
#!/usr/bin/env bash
curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
source "$HOME/.rye/env"
rye sync -f
"""
