name: Prøv lykken (Norsk)
description: Foreslå en oppskrift kun via URL
title: "[RECIPE]: "
labels: ["recipe", "nb", "recipe-scrapers"]
assignees:
  - engeir
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar med en oppskrift! Denne måten å foreslå oppskrifter på
        feiler noen ganger, men ved hjelp av recipe-scrapers klarer vi kanskje å lese
        den inn automatisk. Om den automatiske PR-en feiler, legg inn oppskriften
        manuelt via den andre innmeldingsmetoden.
  - type: input
    id: bidragsyter-url
    attributes:
      label: Lenke
      description: Lim inn lenken til oppskriften.
      placeholder: "f.eks. https://mere.eirik.re/bakst/bananbrod/"
    validations:
      required: true
  - type: input
    id: oppskrift-tittel
    attributes:
      label: Tittel
      description: Hva skal retten hete?
      placeholder: "f.eks. Bananbrød"
    validations:
      required: true
  - type: dropdown
    id: vanskelighetsgrad
    attributes:
      label: Vanskelighetsgrad
      description: Hvor vanskelig er det å lage retten?
      multiple: false
      options:
        - Enkel
        - Middels
        - Vanskelig
    validations:
      required: true
  - type: dropdown
    id: kategori
    attributes:
      label: Kategori
      description: Innen hvilken kategori passer retten?
      options:
        - hovedrett
        - enkel-servering
        - dessert
        - bakst
        - drikke
      default: 0
    validations:
      required: true
  - type: dropdown
    id: emner
    validations:
      required: true
    attributes:
      label: Emner
      description: Hva slags emner passer til retten?
      multiple: true
      options:
        - appelsin
        - aubergine
        - avokado
        - bacon
        - balsamico
        - banan
        - basilikum
        - blåmuggost
        - bolle
        - brød
        - bulgur
        - byggryn
        - bønner
        - couscous
        - curry-on
        - dill
        - drink
        - egg
        - eple
        - fisk
        - fløte
        - frisk
        - frokost
        - gelatin
        - granateple
        - gresskarkjerner
        - grillmat
        - grønne bønner
        - grønnsaksbuljong
        - gulrot
        - halloumi
        - havregryn
        - hvetemel
        - ingefærpasta
        - hvitløk
        - jul
        - kaffe
        - kake
        - kardemumme
        - kjøttdeig
        - kokosmelk
        - konfekt
        - koriander
        - krem
        - kylling
        - løk
        - mais
        - majones
        - mango
        - melk
        - mild mahal
        - nudler
        - ost
        - pasta
        - peanøtt
        - pitabrød
        - pizza
        - potet
        - prosciutto
        - punch
        - pære
        - rask
        - reker
        - ris
        - risotto
        - rødbete
        - røde linser
        - rødkål
        - rødløk
        - rømme
        - safran
        - salat
        - sitrus
        - sjokolade
        - sjømat
        - skinke
        - smør
        - sopp
        - squash
        - sukker
        - sunn
        - suppe
        - taco
        - tilbehør
        - tofu
        - tomat
        - turmat
        - vegansk
        - vegetar
        - vin
        - vodka
        - wok
        - yoghurt
  - type: input
    id: andre-kategorier-emner
    attributes:
      label: Ekstraemner
      description: Er det andre kategorier eller emner som passer?
    validations:
      required: false
