name: Convert issue to PR
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  convert-issue-to-pr-en:
    if: contains(github.event.issue.labels.*.name, 'en') && contains(github.event.issue.labels.*.name, 'recipe')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ github.event.issue.number }}
      - name: Set up environment variables
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "ISSUEUSER=$(curl -s ${{ github.event.issue.user.url }} | jq -r '.name')" >> $GITHUB_ENV
          echo "ISSUEUSER_ID=$(curl -s ${{ github.event.issue.user.url }} | jq -r '.id')" >> $GITHUB_ENV
          if [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" == "" ]]; then echo "CREATOR=$ISSUEUSER" >> $GITHUB_ENV; else echo "CREATOR=${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" >> $GITHUB_ENV; fi
          if [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" == "" ]]; then echo "CREATORTITLE=Person" >> $GITHUB_ENV; elif [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-type }}" == "" ]]; then echo "CREATORTITLE=Person" >> $GITHUB_ENV; else echo "CREATORTITLE=${{ fromJson(steps.parse.outputs.payload).Contributor-type }}" >> $GITHUB_ENV; fi
          if [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" == "" ]]; then echo "CREATORURL=${{ github.event.issue.html_url }}" >> $GITHUB_ENV; else echo "CREATORURL=${{ fromJson(steps.parse.outputs.payload).URL }}" >> $GITHUB_ENV; fi
          echo "TMPDIR=/tmp/src/${{ fromJson(steps.parse.outputs.payload).Category }}" >> $GITHUB_ENV
          echo "TMPFILE=/tmp/src/${{ fromJson(steps.parse.outputs.payload).Category }}/${{ fromJson(steps.parse.outputs.payload).Filename }}.md" >> $GITHUB_ENV
          echo "FILE_REL_TO_ROOT=src/${{ fromJson(steps.parse.outputs.payload).Category }}/${{ fromJson(steps.parse.outputs.payload).Filename }}.md" >> $GITHUB_ENV
      - name: Show parsed payload data
        run: |
          mkdir -p "$TMPDIR"
          touch "$TMPFILE"

          cat << EOF > "$TMPFILE"
          ---
          description: "${{ fromJson(steps.parse.outputs.payload).Time[2] }} | ${{ fromJson(steps.parse.outputs.payload).Difficulty }}"
          authors:
            - name: "$ISSUEUSER (@${{ github.event.issue.user.login }})"
              link: "${{ github.event.issue.user.html_url }}"
              avatar: "${{ github.event.issue.user.avatar_url }}"
          category:
            - $ISSUEUSER
            - ${{ fromJson(steps.parse.outputs.payload).Category }}
          tag:
          EOF
          for tag in ${{ join(fromJson(steps.parse.outputs.payload).Tags, ' ') }}
          do
              echo "  - $tag">>"$TMPFILE"
          done
          cat << EOF >> "$TMPFILE"
          ---

          # ${{ fromJson(steps.parse.outputs.payload).Recipe-name }}

          ![](/static/${{ fromJson(steps.parse.outputs.payload).Filename }}/${{ fromJson(steps.parse.outputs.payload).Filename }}.webp)

          EOF
          if [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" != "" ]] && [[ "${{ fromJson(steps.parse.outputs.payload).URL }}" != "" ]]; then
          cat << EOF >> "$TMPFILE"
          !!!info

          This recipe is originally from
          [!badge variant="dark" iconAlign="right" margin="0 0 0 4" icon=":cook:" size="l" target="blank" text="${{ fromJson(steps.parse.outputs.payload).Contributor-name }}"](${{ fromJson(steps.parse.outputs.payload).URL }})

          !!!

          EOF
          elif [[ "${{ fromJson(steps.parse.outputs.payload).Contributor-name }}" != "" ]]; then
          cat << EOF >> "$TMPFILE"
          !!!info

          This recipe is originally from
          [!badge variant="dark" iconAlign="right" margin="0 0 0 4" icon=":cook:" size="l" target="blank" text="${{ fromJson(steps.parse.outputs.payload).Contributor-name }}"]

          !!!

          EOF
          fi
          cat << EOF >> "$TMPFILE"
          <!-- dprint-ignore-start -->
          ||| :timer_clock: Time
          ${{ fromJson(steps.parse.outputs.payload).Time[2] }}
          ||| :knife_fork_plate: Portions
          ${{ fromJson(steps.parse.outputs.payload).Portions }}
          ||| :cook: Difficulty
          ${{ fromJson(steps.parse.outputs.payload).Difficulty }}
          |||
          <!-- dprint-ignore-end -->

          ## Ingredients

          EOF
          while IFS= read -r ingredient; do
              echo "- $ingredient" >>"$TMPFILE"
          done < <(echo "${{ fromJson(steps.parse.outputs.payload).Ingredients }}")
          cat << EOF >> "$TMPFILE"

          ## Steps

          EOF
          count=1
          while IFS= read -r step; do
              echo "$count. $step">>"$TMPFILE"
              ((count ++))
          done < <(echo "${{ fromJson(steps.parse.outputs.payload).Steps }}")
          cat << EOF >> "$TMPFILE"

          <script type="application/ld+json">
          {
            "@context": "https://schema.org/",
            "@type": "Recipe",
            "name": "${{ fromJson(steps.parse.outputs.payload).Recipe-name }}",
            "image": "/static/${{ fromJson(steps.parse.outputs.payload).Filename }}/${{ fromJson(steps.parse.outputs.payload).Filename }}.webp",
            "author": {
              "@type": "$CREATORTITLE",
              "name": "$CREATOR",
              "url": "$CREATORURL"
            },
            "datePublished": "$DATE",
            "description": "${{ fromJson(steps.parse.outputs.payload).Time[2] }} | ${{ fromJson(steps.parse.outputs.payload).Difficulty }}",
            "prepTime": "${{ fromJson(steps.parse.outputs.payload).Time[0] }}",
            "cookTime": "${{ fromJson(steps.parse.outputs.payload).Time[1] }}",
            "totalTime": "${{ fromJson(steps.parse.outputs.payload).Time[2] }}",
            "recipeYield": "${{ fromJson(steps.parse.outputs.payload).Portions }}",
            "recipeCategory": "${{ fromJson(steps.parse.outputs.payload).Category }}",
            "recipeCuisine": "${{ fromJson(steps.parse.outputs.payload).Cuisine }}",
            "keywords": "${{ join(fromJson(steps.parse.outputs.payload).Tags, ', ') }}",
            "recipeIngredient": [
          EOF
          last_line=""
          while IFS= read -r ingredient; do
              if [[ "$last_line" != "" ]]; then
                  echo "    \"$last_line\"," >>"$TMPFILE"
              fi
              last_line="$ingredient"
          done < <(echo "${{ fromJson(steps.parse.outputs.payload).Ingredients }}")
          echo "    \"$last_line\"" >>"$TMPFILE"
          cat << EOF >> "$TMPFILE"
            ],
            "recipeInstructions": [
          EOF
          last_line=""
          while IFS= read -r step; do
              if [[ "$last_line" != "" ]]; then
                  printf '    {\n      "@type": "HowToStep",\n      "text": "%s"\n    },\n' "$last_line" >>"$TMPFILE"
              fi
              last_line="$step"
          done < <(echo "${{ fromJson(steps.parse.outputs.payload).Steps }}")
          printf '    {\n      "@type": "HowToStep",\n      "text": "%s"\n    }\n' "$last_line" >>"$TMPFILE"
          cat << EOF >> "$TMPFILE"
            ]
          }
          </script>
          EOF
          cat "$TMPFILE"
          mv "$TMPFILE" ./"$FILE_REL_TO_ROOT"
      - name: Update main branch
        run: |
          git pull --rebase
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "${{ fromJson(steps.parse.outputs.payload).Filename }}"
          add-paths: |
            ${{ env.FILE_REL_TO_ROOT }}
          delete-branch: true
          author: ${{ github.event.issue.user.login }} <${{ env.ISSUEUSER_ID }}+${{ github.event.issue.user.login }}@users.noreply.github.com>
          reviewers: ${{ github.repository_owner }}
          assignees: ${{ github.repository_owner }}
          title: "feat(recipe): ${{ fromJson(steps.parse.outputs.payload).Recipe-name }}"
          body: |
            :robot: I just made a PR to add ${{ fromJson(steps.parse.outputs.payload).Recipe-name }} on behalf of [@${{ github.event.issue.user.login }}](${{ github.event.issue.user.html_url }}).

            Resolves #${{ github.event.issue.number }}
          labels: |
            recipe
