name: Labeler
on:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labeler.yml"
  pull_request:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labeler.yml"
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          skip-delete: true
